config/routes.rb
Rails.application.routes.draw do

  root 'frontend#index'

  get 'backend', to: 'backend#index', as: 'backend_index'

  resources :pages

  resources :houses, module: 'frontend', as: 'houses'

  namespace :backend do
    resources :articles
    resources :houses
    resources :pages
    resources :galleries
  end

end

app/models/backend.rb
module Backend
  def self.table_name_prefix
    'backend_'
  end
end

app/models/backend/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  seo_desc   :string(255)
#  seo_kwords :string(255)
#  image_id   :string(255)
#  content    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  category   :string(255)
#  status     :string(255)
#

class Backend::Article < Article
  self.table_name = 'articles'
end

app/models/backend/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  published  :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string(255)
#

class Backend::Gallery < Gallery
  self.table_name = 'galleries'
end

app/models/backend/gallery_item.rb
# == Schema Information
#
# Table name: gallery_items
#
#  id         :integer          not null, primary key
#  gallery_id :integer
#  title      :string(255)
#  image_id   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Backend::GalleryItem < GalleryItem
  self.table_name = 'gallery_items'
end

app/models/backend/house.rb
# == Schema Information
#
# Table name: houses
#
#  id              :integer          not null, primary key
#  title           :string(255)
#  slug            :string(255)
#  keywords        :string(255)
#  desc            :string(255)
#  price           :float(24)
#  price_for_meter :float(24)
#  house_type      :string(255)
#  material        :string(255)
#  etaj            :integer
#  content         :text(65535)
#  home_size       :float(24)
#  land_area       :float(24)
#  city_name       :string(255)
#  location_id     :integer
#  published       :boolean
#  sold            :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Backend::House < House
  self.table_name = 'houses'
end

app/models/backend/page.rb
# == Schema Information
#
# Table name: pages
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  seo_desc   :string(255)
#  seo_kwords :string(255)
#  content    :text(65535)
#  menu_pos   :integer          default(0), not null
#  published  :boolean
#  in_menu    :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :string(255)
#  image_id   :string(255)
#  slug       :string(255)
#

class Backend::Page < Page
  self.table_name = 'pages'
end

app/controllers/backend/articles_controller.rb
class Backend::ArticlesController < BackendController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = Backend::Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Backend::Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Backend::Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Запись была успешно создана'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Запись была успещно обновлена.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to backend_article_url, notice: 'Запись была успешно удалена.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Backend::Article.friendly.find(params[:id])
      @article.category = :article
      @article.save
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:backend_article).permit(:title, :seo_desc, :seo_kwords, :image, :content, :category, :status)
    end
end

app/controllers/backend/galleries_controller.rb
class Backend::GalleriesController < BackendController
  before_action :set_backend_gallery, only: [:show, :edit, :update, :destroy]

  # GET /backend/galleries
  def index
    @galleries = Backend::Gallery.order("created_at DESC").all
    # byebug
  end

  # GET /backend/galleries/1
  def show
  end

  # GET /backend/galleries/new
  def new
    @gallery = Backend::Gallery.new
  end

  # GET /backend/galleries/1/edit
  def edit
  end

  # POST /backend/galleries
  def create
    @gallery = Backend::Gallery.new(gallery_params)

    if @gallery.save
      unless gallery_params[:gallery_items].blank?
        gallery_params[:gallery_items].each do |i|
          image = GalleryItem.new
          image.file = i
          image.save
          @gallery.gallery_items << image
        end
        @gallery.save
      end
      redirect_to @gallery, notice: 'Галерея была успешно создана.'
    else
      render :new
    end
  end

  # PATCH/PUT /backend/galleries/1
  def update
    if @gallery.update(gallery_params)
      redirect_to @gallery, notice: 'Галерея успешно обновлена.'
    else
      render :edit
    end
  end

  # DELETE /backend/galleries/1
  def destroy
    @gallery.destroy
    redirect_to backend_galleries_url, notice: 'Галерея успешно удалена.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backend_gallery
      @gallery = Backend::Gallery.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gallery_params
      params.require(:backend_gallery).permit(:name, :title, :published,  gallery_items_attributes: [:id, :image, :_destroy])
    end
end

app/controllers/backend/houses_controller.rb
class Backend::HousesController < BackendController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = Backend::House.order("created_at DESC").paginate(:page => params[:page])
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = Backend::House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    # @house = House.new(house_params.except(:images))
    @house = Backend::House.new(house_params)
    respond_to do |format|
      if @house.save
        @house.price_for_meter = @house.price / @house.home_size
        unless house_params[:images].blank?
          house_params[:images].each do |i|
            image = Image.new
            image.file = i
            image.save
            @house.images << image
          end
          @house.save
        end
        format.html { redirect_to backend_houses_path(@house), notice: 'Дом был успешно добавлен.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    # raise @house
    respond_to do |format|
      if @house.update(house_params)

        format.html { redirect_to backend_houses_url, notice: 'Дом был успешно обновлен.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to backend_houses_url, notice: 'Дом был успешно удален.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = Backend::House.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:backend_house).permit( :title, :keywords, :desc, :price, :house_type, :material, :etaj, :content, :home_size, :land_area, :city_name, :location_id, :published, :sold, images: [], images_attributes: [:id, :file, :_destroy])
    end
end

app/controllers/backend/pages_controller.rb
class Backend::PagesController < BackendController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  def index
    @pages = Backend::Page.all
  end

  # GET /pages/1
  def show
  end

  # GET /pages/new
  def new
    @page = Backend::Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  def create
    @page = Backend::Page.new(page_params)
    # byebug
    if @page.save
      redirect_to @page, notice: 'Page was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /pages/1
  def update
    if @page.update(page_params)
      redirect_to @page, notice: 'Page was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /pages/1
  def destroy
    @page.destroy
    redirect_to backend_pages_url, notice: 'Страница была успешно удалена.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Backend::Page.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def page_params
      params.require(:backend_page).permit(:title, :seo_desc, :seo_kwords, :content, :menu_pos, :in_menu, :status, :image)
    end
end

app/controllers/backend/projects_controller.rb
class Backend::ProjectsController < ApplicationController
  def index
  end

  def show
  end

  def set_project
  end
end

app/controllers/backend_controller.rb
class BackendController < ActionController::Base
  http_basic_authenticate_with name: "admin", password: "ytjkbn"

  def index
  end

end

app/helpers/backend/galleries_helper.rb
module Backend::GalleriesHelper
end

app/helpers/backend/projects_helper.rb
module Backend::ProjectsHelper
end

app/views/backend/pages/_form.html.erb
<%= simple_form_for @page, :html => { :class => 'form-horizontal' } do |f| %>
    <div class="row">
      <div class="col-md-10">
        <%= f.input :title, label: 'Заголовок' %>
        <%= error_span(@page[:title]) %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-10">
        <%= f.input :seo_desc, label: "Описание сео" %>
        <%= error_span(@page[:seo_desc]) %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-10">
        <%= f.input :seo_kwords, label: "Ключевые слова сео" %>
        <%= error_span(@page[:seo_kwords]) %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-5">
        <%= f.input :in_menu, as: :boolean, label: "В меню?" %>
        <%= error_span(@page[:in_menu]) %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-5">
        <%= f.input :menu_pos, label: "Позиция" %>
        <%= error_span(@page[:menu_pos]) %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <label for="backend_page_image">Картинка</label>
        <%= image_tag(attachment_url(@page, :image, :fill, 32, 32, format: "jpg")) if attachment_url(@page, :image)  %>
      </div>
      <div class="col-md-8">
        <%= f.attachment_field :image %>
        <%= error_span(@page[:image]) %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-10">
        <%= f.text_area :content, label: "Текст страницы", class: 'redactor', :rows => 40, :cols => 120 %>
        <%= error_span(@page[:content]) %>

      </div>
    </div>

    <div class="row">
      <div class="col-md-1">
        Статус:
      </div>
      <div class="col-md-8">
        <%= f.select :status, options_for_select(Page.statuses.map {|k, v| [v.humanize.capitalize, k]}, @page.status) , {label: "Статус" } %>
        <%= error_span(@page[:status]) %>
      </div>
    </div>

    <br/>

    <%= f.submit 'Сохранить', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                backend_pages_path, :class => 'btn btn-default' %>
<% end %>
<br/>

<% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>
      <ul>
        <% @page.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/backend/pages/edit.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/backend/pages/index.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1>Страницы</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th># </th>
      <th>Заголовок</th>
      <th>Содержание</th>
      <th>Картинка</th>
      <th>Позиция</th>
      <th>В меню?</th>
      <th>Статус</th>
      <th>Создано</th>
      <th rowspan="2"><%=t '.actions', :default => t("helpers.actions") %></th>
        <th></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to page.id, backend_page_path(page) %></td>
        <td><%= page.title %></td>
        <td><%= truncate strip_tags(page.content), length: 40  %></td>
        <td><%= image_tag(attachment_url(page, :image, :fill, 40, 40, format: "jpg")) if attachment_url(page, :image) %></td>
        <td><%= page.menu_pos %></td>
        <td><%= page.in_menu ? 'ДА' : 'НЕТ' %></td>
        <td><span class="label label-info"><%= Page.statuses[page.status] %></span></td>

        <td><%= Russian::strftime(page.created_at, "%d %B") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_backend_page_path(page), :class => 'btn btn-default btn-xs' %>
        </td><td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      backend_page_path(page),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => 'Новая страница'),
            new_backend_page_path,
            :class => 'btn btn-primary' %>

app/views/backend/pages/new.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1>Новая страница</h1>
</div>
<div class="row">
  <div class="col-md-10">

    <%= render :partial => 'form' %>

  </div>
</div>

app/views/backend/pages/show.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @page.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:seo_desc) %>:</strong></dt>
  <dd><%= @page.seo_desc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:seo_kwords) %>:</strong></dt>
  <dd><%= @page.seo_kwords %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @page.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:menu_pos) %>:</strong></dt>
  <dd><%= @page.menu_pos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:published) %>:</strong></dt>
  <dd><%= @page.published %></dd>
  <dt><strong><%= model_class.human_attribute_name(:in_menu) %>:</strong></dt>
  <dd><%= @page.in_menu %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @page.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_id) %>:</strong></dt>
  <dd><%= @page.image_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              backend_pages_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_backend_page_path(@page), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              backend_page_path(@page),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>