config/routes.rb
Rails.application.routes.draw do

  root 'frontend#index'

  get 'backend', to: 'backend#index', as: 'backend_index'

  resources :pages

  resources :houses, module: 'frontend', as: 'houses'

  namespace :backend do
    resources :articles
    resources :houses
    resources :pages
    resources :galleries
  end

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  seo_desc   :string(255)
#  seo_kwords :string(255)
#  image_id   :string(255)
#  content    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  category   :string(255)
#  status     :string(255)
#

class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, :use => :slugged
  attachment :image
  enum category: {
           article: "Статья",
           post: "Пост блога"
  }
  enum status: {
           draft: "Черновик",
           published: "Опубликован",
           archived: "В архиве"
  }

  validates_presence_of :title, :content, :category
  validates_uniqueness_of :title

  validates :title, length: { minimum: 5 }
  validates :content, length: { minimum: 5 }

end

app/models/backend/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  seo_desc   :string(255)
#  seo_kwords :string(255)
#  image_id   :string(255)
#  content    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  category   :string(255)
#  status     :string(255)
#

class Backend::Article < Article
  self.table_name = 'articles'
end

app/controllers/backend/articles_controller.rb
class Backend::ArticlesController < BackendController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = Backend::Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Backend::Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Backend::Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Запись была успешно создана'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Запись была успещно обновлена.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to backend_article_url, notice: 'Запись была успешно удалена.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Backend::Article.friendly.find(params[:id])
      @article.category = :article
      @article.save
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:backend_article).permit(:title, :seo_desc, :seo_kwords, :image, :content, :category, :status)
    end
end

app/controllers/frontend/articles_controller.rb
class Backend::ArticlesController < BackendController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:title, :seo_desc, :seo_kwords, :image, :content, :category_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= error_span(@article[:title]) %>
  <%= f.input :slug %>
  <%= error_span(@article[:slug]) %>
  <%= f.input :seo_desc %>
  <%= error_span(@article[:seo_desc]) %>
  <%= f.input :seo_kwords %>
  <%= error_span(@article[:seo_kwords]) %>
  <%= f.input :image %>
  <%= error_span(@article[:image]) %>
  <%= f.input :content %>
  <%= error_span(@article[:content]) %>
  <%= f.input :category %>
  <%= error_span(@article[:category]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn btn-default' %>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:slug) %></th>
      <th><%= model_class.human_attribute_name(:seo_desc) %></th>
      <th><%= model_class.human_attribute_name(:seo_kwords) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.id, article_path(article) %></td>
        <td><%= article.title %></td>
        <td><%= article.slug %></td>
        <td><%= article.seo_desc %></td>
        <td><%= article.seo_kwords %></td>
        <td><%= article.image %></td>
        <td><%= article.content %></td>
        <td><%= article.category %></td>
        <td><%=l article.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_article_path(article), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      article_path(article),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_path,
            :class => 'btn btn-primary' %>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @article.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:slug) %>:</strong></dt>
  <dd><%= @article.slug %></dd>
  <dt><strong><%= model_class.human_attribute_name(:seo_desc) %>:</strong></dt>
  <dd><%= @article.seo_desc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:seo_kwords) %>:</strong></dt>
  <dd><%= @article.seo_kwords %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @article.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @article.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @article.category %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>