config/routes.rb
Rails.application.routes.draw do

  root 'frontend#index'

  get 'backend', to: 'backend#index', as: 'backend_index'

  resources :pages

  resources :houses, module: 'frontend', as: 'houses'

  namespace :backend do
    resources :articles
    resources :houses
    resources :pages
    resources :galleries
  end

end

app/models/backend.rb
module Backend
  def self.table_name_prefix
    'backend_'
  end
end

app/models/backend/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  slug       :string(255)
#  seo_desc   :string(255)
#  seo_kwords :string(255)
#  image_id   :string(255)
#  content    :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  category   :string(255)
#  status     :string(255)
#

class Backend::Article < Article
  self.table_name = 'articles'
end

app/models/backend/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  published  :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string(255)
#

class Backend::Gallery < Gallery
  self.table_name = 'galleries'
end

app/models/backend/gallery_item.rb
# == Schema Information
#
# Table name: gallery_items
#
#  id         :integer          not null, primary key
#  gallery_id :integer
#  title      :string(255)
#  image_id   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Backend::GalleryItem < GalleryItem
  self.table_name = 'gallery_items'
end

app/models/backend/house.rb
# == Schema Information
#
# Table name: houses
#
#  id              :integer          not null, primary key
#  title           :string(255)
#  slug            :string(255)
#  keywords        :string(255)
#  desc            :string(255)
#  price           :float(24)
#  price_for_meter :float(24)
#  house_type      :string(255)
#  material        :string(255)
#  etaj            :integer
#  content         :text(65535)
#  home_size       :float(24)
#  land_area       :float(24)
#  city_name       :string(255)
#  location_id     :integer
#  published       :boolean
#  sold            :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Backend::House < House
  self.table_name = 'houses'
end

app/models/backend/page.rb
# == Schema Information
#
# Table name: pages
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  seo_desc   :string(255)
#  seo_kwords :string(255)
#  content    :text(65535)
#  menu_pos   :integer          default(0), not null
#  published  :boolean
#  in_menu    :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :string(255)
#  image_id   :string(255)
#  slug       :string(255)
#

class Backend::Page < Page
  self.table_name = 'pages'
end

app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  published  :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string(255)
#

class Gallery < ActiveRecord::Base
  has_many :gallery_items
  accepts_nested_attributes_for :gallery_items, :allow_destroy => true

  validates_presence_of :title, :name
  validates_uniqueness_of :title, :name

  validates :title, length: { minimum: 3 }
  validates :name, length: { minimum: 3 }
end

app/controllers/backend/articles_controller.rb
class Backend::ArticlesController < BackendController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = Backend::Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Backend::Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Backend::Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Запись была успешно создана'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Запись была успещно обновлена.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to backend_article_url, notice: 'Запись была успешно удалена.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Backend::Article.friendly.find(params[:id])
      @article.category = :article
      @article.save
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:backend_article).permit(:title, :seo_desc, :seo_kwords, :image, :content, :category, :status)
    end
end

app/controllers/backend/galleries_controller.rb
class Backend::GalleriesController < BackendController
  before_action :set_backend_gallery, only: [:show, :edit, :update, :destroy]

  # GET /backend/galleries
  def index
    @galleries = Backend::Gallery.order("created_at DESC").all
    # byebug
  end

  # GET /backend/galleries/1
  def show
  end

  # GET /backend/galleries/new
  def new
    @gallery = Backend::Gallery.new
  end

  # GET /backend/galleries/1/edit
  def edit
  end

  # POST /backend/galleries
  def create
    @gallery = Backend::Gallery.new(gallery_params)

    if @gallery.save
      unless gallery_params[:gallery_items].blank?
        gallery_params[:gallery_items].each do |i|
          image = GalleryItem.new
          image.file = i
          image.save
          @gallery.gallery_items << image
        end
        @gallery.save
      end
      redirect_to @gallery, notice: 'Галерея была успешно создана.'
    else
      render :new
    end
  end

  # PATCH/PUT /backend/galleries/1
  def update
    if @gallery.update(gallery_params)
      redirect_to @gallery, notice: 'Галерея успешно обновлена.'
    else
      render :edit
    end
  end

  # DELETE /backend/galleries/1
  def destroy
    @gallery.destroy
    redirect_to backend_galleries_url, notice: 'Галерея успешно удалена.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backend_gallery
      @gallery = Backend::Gallery.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gallery_params
      params.require(:backend_gallery).permit(:name, :title, :published,  gallery_items_attributes: [:id, :image, :_destroy])
    end
end

app/controllers/backend/houses_controller.rb
class Backend::HousesController < BackendController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = Backend::House.order("created_at DESC").paginate(:page => params[:page])
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = Backend::House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    # @house = House.new(house_params.except(:images))
    @house = Backend::House.new(house_params)
    respond_to do |format|
      if @house.save
        @house.price_for_meter = @house.price / @house.home_size
        unless house_params[:images].blank?
          house_params[:images].each do |i|
            image = Image.new
            image.file = i
            image.save
            @house.images << image
          end
          @house.save
        end
        format.html { redirect_to backend_houses_path(@house), notice: 'Дом был успешно добавлен.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    # raise @house
    respond_to do |format|
      if @house.update(house_params)

        format.html { redirect_to backend_houses_url, notice: 'Дом был успешно обновлен.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to backend_houses_url, notice: 'Дом был успешно удален.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = Backend::House.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:backend_house).permit( :title, :keywords, :desc, :price, :house_type, :material, :etaj, :content, :home_size, :land_area, :city_name, :location_id, :published, :sold, images: [], images_attributes: [:id, :file, :_destroy])
    end
end

app/controllers/backend/pages_controller.rb
class Backend::PagesController < BackendController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  def index
    @pages = Backend::Page.all
  end

  # GET /pages/1
  def show
  end

  # GET /pages/new
  def new
    @page = Backend::Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  def create
    @page = Backend::Page.new(page_params)
    # byebug
    if @page.save
      redirect_to @page, notice: 'Page was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /pages/1
  def update
    if @page.update(page_params)
      redirect_to @page, notice: 'Page was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /pages/1
  def destroy
    @page.destroy
    redirect_to backend_pages_url, notice: 'Страница была успешно удалена.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Backend::Page.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def page_params
      params.require(:backend_page).permit(:title, :seo_desc, :seo_kwords, :content, :menu_pos, :in_menu, :status, :image)
    end
end

app/controllers/backend/projects_controller.rb
class Backend::ProjectsController < ApplicationController
  def index
  end

  def show
  end

  def set_project
  end
end

app/controllers/backend_controller.rb
class BackendController < ActionController::Base
  http_basic_authenticate_with name: "admin", password: "ytjkbn"

  def index
  end

end

app/helpers/backend/galleries_helper.rb
module Backend::GalleriesHelper
end

app/helpers/backend/projects_helper.rb
module Backend::ProjectsHelper
end

app/views/backend/galleries/_form.html.erb
<%= simple_nested_form_for @gallery, :html => { :class => 'form-horizontal' } do |f| %>

    <div class="row">
      <div class="col-md-4">
        <%= f.input :title, label: 'Заголовок' %>
        <%= error_span(@gallery[:title]) %>

      </div>
    </div>

    <div class="row">
        <div class="col-md-4">
          <%= f.input :name, label: 'Название' %>
          <%= error_span(@gallery[:name]) %>
        </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <table id="gallery_items">
          <%= f.simple_fields_for :gallery_items, :wrapper => false do |image_form| %>
              <tr class="fields">
                <td><%= image_form.input :title, label: 'Название' %> </td>
                <td><%= image_tag(attachment_url(image_form.object, :image, :fill, 32, 32, format: "jpg"))  %></td>
                <td><%= image_form.file_field :image, label: "Файл" %></td>
                <td><%= image_form.link_to_remove "Удалить", class:"btn btn-small btn-danger" %></td>
              </tr>
          <% end %>
        </table>
        <p><%= f.link_to_add "Добавить изображение", :gallery_items, :data => { :target => "#gallery_items" }, :class => 'btn btn-small btn-primary' %></p>
      </div>
    </div>


  <%= f.input :published, label: 'Опубликовано' %>
  <%= error_span(@gallery[:published]) %>

  <%= f.button :submit, :class => 'btn-primary', label: 'Сохранить' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                backend_galleries_path, :class => 'btn btn-default' %>
<% end %>

app/views/backend/galleries/edit.html.erb
<%- model_class = Backend::Gallery -%>
<div class="page-header">
    <h1>Изменить галерею</h1>
</div>
<%= render :partial => 'form' %>

app/views/backend/galleries/index.html.erb
<%- model_class = Backend::Gallery -%>
<div class="page-header">
  <h1>Галереи</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Заголовок</th>
      <th>Название</th>
      <th>Статус</th>
      <th>Создано</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= link_to gallery.id, backend_gallery_path(gallery) %></td>
        <td><%= gallery.title %></td>
        <td><%= gallery.name %></td>
        <td><% if gallery.published? %>
              <span class="label label-success">Опубликовано</span>
          <% else %>
              <span class="label label-warning">Не опубликовано</span>
          <% end %>
        </td>
        <td><%=Russian::strftime(gallery.created_at, "%d %B")  %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_backend_gallery_path(gallery), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      backend_gallery_path(gallery),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => "Новая галерея"),
            new_backend_gallery_path,
            :class => 'btn btn-success' %>

app/views/backend/galleries/new.html.erb
<%- model_class = Backend::Gallery -%>
<div class="page-header">
    <h1>Новая галерея</h1>
</div>
<%= render :partial => 'form' %>

app/views/backend/galleries/show.html.erb
<%- model_class = Backend::Gallery -%>
<div class="page-header">
    <h1>Галерея</h1>
</div>
<h3>Изображений в галерее <%= @gallery.gallery_items.count %></h3>
<dl class="dl-horizontal">
  <dt><strong>Заголовок:</strong></dt>
  <dd><%= @gallery.title %></dd>
  <dt><strong>Название:</strong></dt>
  <dd><%= @gallery.name %></dd>
  <dt><strong>Опубликовано:</strong></dt>
  <dd><%= @gallery.published %></dd>
</dl>



<%= link_to t('.back', :default => t("helpers.links.back")),
              backend_galleries_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_backend_gallery_path(@gallery), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              backend_gallery_path(@gallery),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>