config/routes.rb
Rails.application.routes.draw do

  root 'frontend#index'

  get 'backend', to: 'backend#index', as: 'backend_index'

  resources :pages

  resources :houses, module: 'frontend', as: 'houses'

  namespace :backend do
    resources :articles
    resources :houses
    resources :pages
    resources :galleries
  end

end

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Akyort" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "backend.css", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "backend" %>
    <%=   %>

  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/backend">Админка</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <%= active_link_to "Дома", backend_houses_path, :wrap_tag => :li %>
            <%= active_link_to "Статьи", backend_articles_path, :wrap_tag => :li %>
            <%= active_link_to "Страницы", backend_pages_path, :wrap_tag => :li  %>
            <%= active_link_to "Галереи", backend_galleries_path, :wrap_tag => :li  %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; АкЙорт 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/frontend.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="icon" href="../../favicon.ico">


    <title><%=  yield(:title) if content_for?(:title)%> | АкЙорт недвижимость</title>
    <meta name="description" content="<%=  yield(:desc) if content_for?(:desc)%>">
    <meta name="keywords" content="<%=  yield(:keys) if content_for?(:keys)%>">
    <%= csrf_meta_tags %>
    <!-- Bootstrap core CSS -->

    <!-- Latest compiled and minified CSS -->
    <%= stylesheet_link_tag "frontend/application", :media => "all" %>
    <link rel="stylesheet" href="/bower_components/jquery-colorbox/colorbox.css"/>


    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,700italic&subset=latin,cyrillic,cyrillic-ext' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="/bower_components/html5shiv/dist/html5shiv.min.js"></script>
    <script src="/bower_components/respond/dest/respond.min.js"></script>

    <![endif]-->

    <link rel="stylesheet" href="/css/all.css"/>
    <link rel="stylesheet" href="/css/non-responsive.css"/>
    <style>

        body {

            padding-top: 0px !important;
        }

        #ux-header-image {
            margin-top: 16px;
            margin-left: 8px;
        }


    </style>
  <%= javascript_include_tag "frontend/application" %>
</head>

<body>

<div class="container" id="ux-container">

    <div class="row" id="ux-header">

        <div class="col-md-5">

            <p id="ux-header-text-main">
                <a href="/" > ДОМ ВАШЕЙ МЕЧТЫ </a>
            </p>

            <p id="ux-header-text-small">
                загородные дома по цене квартиры
            </p>

        </div>

        <div class="col-md-3">

            <div id="ux-header-image">
                <a href="/">
                    <img src="/images/logo.png" alt=""/>
                </a>

            </div>

        </div>

        <div class="col-md-4">

            <div id="ux-header-contacts">

                <p id="ux-header-phone">

                    8(347) 312 34 55
                </p>

                <p id="ux-header-worktime">

                    с 10:00 до 20:00
                </p>

                <a href="#callbackhunter">
                    <p id="ux-header-callback">


                        ЗАКАЗАТЬ ОБРАТНЫЙ ЗВОНОК

                    </p>
                </a>
            </div>


        </div>

    </div>


    <div class="row">

        <div class="ux-hr"></div>

        <div class="main_menu">

            <!--@include('menu')-->

        </div>



    </div>


    <div class="row" id="ux-gallery">
        <div class="col-md-12"></div>
    </div>

    <div class="ux-hr" style="width:940px" ></div>


    <%= yield %>

    <div class="row" >

        <div id="footer">


            <div class="col-md-4">

                <ul class="list-unstyled">

                    <li> <a href="/houses">Все дома</a> </li>
                    <li> <a href="/projects">Проекты</a> </li>
                    <li> <a href="/pages/uslugi">Услуги</a> </li>
                </ul>

            </div>
            <div class="col-md-4"></div>
            <div class="col-md-4"></div>


        </div>

    </div>


</div>    <!-- /container -->



</body>
</html>